######################################################################################
#  _    _ __     __ _____   _____   _                 _   _  _____  
# | |  | |\ \   / /|  __ \ |  __ \ | |         /\    | \ | ||  __ \ 
# | |__| | \ \_/ / | |__) || |__) || |        /  \   |  \| || |  | |
# |  __  |  \   /  |  ___/ |  _  / | |       / /\ \  | . ` || |  | |
# | |  | |   | |   | |     | | \ \ | |____  / ____ \ | |\  || |__| |
# |_|  |_|   |_|   |_|     |_|  \_\|______|/_/    \_\|_| \_||_____/ 
######################################################################################

source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/permissions.conf
source = ~/.config/hypr/conf/style.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/binds.conf
source = ~/.config/hypr/conf/rules.conf
