$background = fffaff
$onBackground = 1f1a1c
$surface = fffaff
$surfaceDim = f2e6e8
$surfaceBright = fffaff
$surfaceContainerLowest = ffffff
$surfaceContainerLow = fff6f7
$surfaceContainer = fdf2f4
$surfaceContainerHigh = faeff0
$surfaceContainerHighest = f7ebee
$onSurface = 1f1a1c
$surfaceVariant = fde9ef
$onSurfaceVariant = 4f4448
$outline = 817378
$outlineVariant = d3c2c7
$inverseSurface = 342f31
$inverseOnSurface = f8eef0
$shadow = 000000
$scrim = 000000
$surfaceTint = c789a4
$primary = 7e5165
$primaryDim = 714559
$onPrimary = ffffff
$primaryContainer = e1a9c0
$onPrimaryContainer = 663c4f
$inversePrimary = f0b7ce
$primaryFixed = ffd8e6
$primaryFixedDim = f0b7ce
$onPrimaryFixed = 320f21
$onPrimaryFixedVariant = 643a4d
$secondary = 6f5861
$secondaryDim = 624c55
$onSecondary = ffffff
$secondaryContainer = f6d8e2
$onSecondaryContainer = 735c65
$secondaryFixed = f9dbe5
$secondaryFixedDim = dcbfc9
$onSecondaryFixed = 27171e
$onSecondaryFixedVariant = 564149
$tertiary = 84523d
$tertiaryDim = 764632
$onTertiary = ffffff
$tertiaryContainer = e9aa90
$onTertiaryContainer = 6b3d29
$tertiaryFixed = ffdbcd
$tertiaryFixedDim = f9b89d
$onTertiaryFixed = 331103
$onTertiaryFixedVariant = 683b27
$error = ba1a1a
$errorDim = a80710
$onError = ffffff
$errorContainer = ffdad6
$onErrorContainer = 93000a
$primaryPaletteKeyColor = 9a697e
$secondaryPaletteKeyColor = 897079
$tertiaryPaletteKeyColor = e9aa90
$neutralPaletteKeyColor = 7c7577
$neutralVariantPaletteKeyColor = 817378
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 9a697e
$secondary_paletteKeyColor = 897079
$tertiary_paletteKeyColor = e9aa90
$neutral_paletteKeyColor = 7c7577
$neutral_variant_paletteKeyColor = 817378
$term0 = cebebd
$term1 = b1266f
$term2 = c96245
$term3 = ac536d
$term4 = cc6c77
$term5 = b03f80
$term6 = 9073b8
$term7 = 262123
$term8 = 100f0f
$term9 = d04087
$term10 = f18062
$term11 = cd6e89
$term12 = f58d98
$term13 = d0599c
$term14 = b193da
$term15 = 2c2729
$rosewater = af687e
$flamingo = b1597b
$pink = c95295
$mauve = 9e0082
$red = a6005e
$maroon = bd226f
$peach = d63373
$yellow = c75a72
$green = c04800
$teal = 745ca0
$sky = ab5caf
$sapphire = 8b61a9
$blue = 9b1f93
$lavender = b04aa1
$klink = b36fb2
$klinkSelection = b46fb2
$kvisited = c15d9d
$kvisitedSelection = c25d9c
$knegative = e64f93
$knegativeSelection = e64f92
$kneutral = ff84a6
$kneutralSelection = ff84a5
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = 1f1a1c
$subtext1 = 4f4448
$subtext0 = 817378
$overlay2 = c5afb8
$overlay1 = cdbcc5
$overlay0 = d6c7d1
$surface2 = e0d3db
$surface1 = e9e0e7
$surface0 = f4eef4
$base = fffcff
$mantle = fbf7fb
$crust = f8f3f7
$success = 4F6354
$onSuccess = FFFFFF
$successContainer = D1E8D5
$onSuccessContainer = 0C1F13
