######################################################################################
#            _    _  _______   ____    _____  _______            _____  _______ 
#     /\    | |  | ||__   __| / __ \  / ____||__   __|    /\    |  __ \|__   __|
#    /  \   | |  | |   | |   | |  | || (___     | |      /  \   | |__) |  | |   
#   / /\ \  | |  | |   | |   | |  | | \___ \    | |     / /\ \  |  _  /   | |   
#  / ____ \ | |__| |   | |   | |__| | ____) |   | |    / ____ \ | | \ \   | |   
# /_/    \_\ \____/    |_|    \____/ |_____/    |_|   /_/    \_\|_|  \_\  |_|   
######################################################################################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = $terminal
exec-once = caelestia shell
#exec-once = hyprpaper
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = hyprctl setcursor phinger-cursors-light 24
exec-once = gsettings set org.gnome.desktop.interface icon-theme 'Tela-circle-red'
