######################################################################################
#  ______  _   _ __      __ _____  _____    ____   _   _  __  __  ______  _   _  _______ 
# |  ____|| \ | |\ \    / /|_   _||  __ \  / __ \ | \ | ||  \/  ||  ____|| \ | ||__   __|
# | |__   |  \| | \ \  / /   | |  | |__) || |  | ||  \| || \  / || |__   |  \| |   | |   
# |  __|  | . ` |  \ \/ /    | |  |  _  / | |  | || . ` || |\/| ||  __|  | . ` |   | |   
# | |____ | |\  |   \  /    _| |_ | | \ \ | |__| || |\  || |  | || |____ | |\  |   | |   
# |______||_| \_|    \/    |_____||_|  \_\ \____/ |_| \_||_|  |_||______||_| \_|   |_|   
######################################################################################

# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = XCURSOR_THEME,phinger-cursors-light
env = GDK_BACKEND,wayland,x11,*
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

