######################################################################################
#  __  __   ____   _   _  _____  _______   ____   _____    _____ 
# |  \/  | / __ \ | \ | ||_   _||__   __| / __ \ |  __ \  / ____|
# | \  / || |  | ||  \| |  | |     | |   | |  | || |__) || (___  
# | |\/| || |  | || . ` |  | |     | |   | |  | ||  _  /  \___ \ 
# | |  | || |__| || |\  | _| |_    | |   | |__| || | \ \  ____) |
# |_|  |_| \____/ |_| \_||_____|   |_|    \____/ |_|  \_\|_____/ 
######################################################################################

# See https://wiki.hypr.land/Configuring/Monitors/
#monitor=,preferred,auto,auto

monitor = HDMI-A-1, 1920x1080@100, 0x0, 1
