######################################################################################
#  _____   _____    ____    _____  _____            __  __   _____ 
# |  __ \ |  __ \  / __ \  / ____||  __ \    /\    |  \/  | / ____|
# | |__) || |__) || |  | || |  __ | |__) |  /  \   | \  / || (___  
# |  ___/ |  _  / | |  | || | |_ ||  _  /  / /\ \  | |\/| | \___ \ 
# | |     | | \ \ | |__| || |__| || | \ \ / ____ \ | |  | | ____) |
# |_|     |_|  \_\ \____/  \_____||_|  \_/_/    \_\|_|  |_||_____/ 
######################################################################################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$menu = wofi

