cursor_shape beam
cursor_trail 1
confim_os_window_close 0
shell zsh
window_padding_width 5

# Podstawowe kolory tła i tekstu
foreground            #191c1e
background            #ffffff
selection_foreground  #ffffff
selection_background  #4c606f

# Kolor kursora
cursor                #4c606f
cursor_text_color     #ffffff

# Kolory URL (linki)
url_color             #4c606f

# Okno i obramowanie
active_border_color   #4c606f
inactive_border_color #c4c7cf

# Tab bar
active_tab_foreground   #ffffff
active_tab_background   #4c606f
inactive_tab_foreground #43474e
inactive_tab_background #eeeff3

# Paleta kolorów
# Black
color0 #191c1e
color8 #74777f
# Red
color1 #ba1a1a
color9 #ffdad6
# Green
color2 #4c606f
color10 #b2c9db
# Yellow
color3 #e0af68
color11 #f3e2ad
# Blue
color4 #4c606f
color12 #b2c9db
# Magenta
color5 #625b71
color13 #cbc2db
# Cyan
color6 #4c606f
color14 #b2c9db
# White
color7 #ffffff
color15 #f3f3f7
